Repository Codersweta7/BLOGGING, pull requests merged in 2025-02, with the labels that each got.

#18 added footer
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/Componrnts/Footer.js
  src/Componrnts/Layout.js
  yarn.lock
Labels: JWOC, 1

#26 Implemented search functionality using React Context
  src/App.css
  src/Componrnts/Entry.js
  src/Componrnts/Header.js
  src/Componrnts/Layout.js
  src/context/SearchContext.js
  src/data/data.json
Labels: 3, JWOC

#27 Added ThemeContext to manage dark mode and applied dark mode styles on all components.
  src/App.css
  src/Componrnts/Header.js
  src/context/ThemeContext.js
  src/index.css
  src/index.js
Labels: JWOC, 1

#33 Feedback
  package-lock.json
  package.json
  src/Componrnts/Feedback.js
  yarn.lock
Labels: 3, JWOC

#37 Fix-issue-21
  server/db/index.js
  server/routes/admin.js
  server/routes/user.js
Labels: Medium, JWOC

#36 about page created
  src/App.js
  src/Pages/About.css
  src/Pages/About.js
Labels: JWOC, Easy

#50 Added meta description and title for better SEO description and title for better SEO
  public/index.html
Labels: JWOC, Easy

#51 ✨ Enhanced README.md with Structured Details & JWOC Info
  README.md
Labels: Medium, JWOC

#52 Modify About Us Page
  src/Pages/About.css
  src/Pages/About.js
Labels: JWOC, Easy

#53 faq section added
  package-lock.json
  package.json
  src/App.js
  src/Componrnts/FAQ.css
  src/Componrnts/Faq.js
  src/Componrnts/Footer.js
  yarn.lock
Labels: JWOC, Easy

#66 added a scroll to top button
  package-lock.json
  package.json
  src/App.js
  src/Componrnts/ScrollToTop.jsx
  yarn.lock
Labels: JWOC, Easy

#71 footer improved
  package-lock.json
  server/.env
  src/Componrnts/Footer.js
  yarn.lock
Labels: JWOC, Easy

#73 changed the twitter icon to 'X'
  package-lock.json
  package.json
  src/App.css
  src/Componrnts/Entry.js
  src/Componrnts/Footer.js
  src/Componrnts/Header.js
  yarn.lock
Labels: JWOC, Easy

#77 added scroll effect
  package-lock.json
  package.json
  src/Componrnts/Entry.js
Labels: JWOC, Easy

#83 fixed navbar overlapping issue!
  package-lock.json
  package.json
  src/Componrnts/Header.js
  yarn.lock
Labels: JWOC, Easy
